name: ESLint - Expo Project

on:
    push:
        branches: [main, dev]
        paths: ["rotary-yep-nl/**"]
    pull_request:
        branches: [main, dev]
        paths: ["rotary-yep-nl/**"]

jobs:
    eslint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "22"
                  cache: "npm"
                  cache-dependency-path: "rotary-yep-nl/package-lock.json"

            - name: Install dependencies
              working-directory: ./rotary-yep-nl
              run: npm ci

            - name: Run Expo Lint with SARIF output
              working-directory: ./rotary-yep-nl
              run: |
                  npx eslint . --ext .js,.jsx,.ts,.tsx --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif || true
              continue-on-error: true

            - name: Upload SARIF file for PR annotations
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: rotary-yep-nl/eslint-results.sarif
                  category: eslint-expo
              if: always()

            - name: Run Expo Lint for terminal output
              working-directory: ./rotary-yep-nl
              run: npx expo lint
