import type { ImageSource } from "expo-image";

// Import all flag SVGs
const flagAssets: Record<string, ImageSource> = {
	ad: require("../assets/flags/ad.svg"),
	ae: require("../assets/flags/ae.svg"),
	af: require("../assets/flags/af.svg"),
	ag: require("../assets/flags/ag.svg"),
	ai: require("../assets/flags/ai.svg"),
	al: require("../assets/flags/al.svg"),
	am: require("../assets/flags/am.svg"),
	ao: require("../assets/flags/ao.svg"),
	aq: require("../assets/flags/aq.svg"),
	ar: require("../assets/flags/ar.svg"),
	as: require("../assets/flags/as.svg"),
	at: require("../assets/flags/at.svg"),
	au: require("../assets/flags/au.svg"),
	aw: require("../assets/flags/aw.svg"),
	ax: require("../assets/flags/ax.svg"),
	az: require("../assets/flags/az.svg"),
	ba: require("../assets/flags/ba.svg"),
	bb: require("../assets/flags/bb.svg"),
	bd: require("../assets/flags/bd.svg"),
	be: require("../assets/flags/be.svg"),
	bf: require("../assets/flags/bf.svg"),
	bg: require("../assets/flags/bg.svg"),
	bh: require("../assets/flags/bh.svg"),
	bi: require("../assets/flags/bi.svg"),
	bj: require("../assets/flags/bj.svg"),
	bl: require("../assets/flags/bl.svg"),
	bm: require("../assets/flags/bm.svg"),
	bn: require("../assets/flags/bn.svg"),
	bo: require("../assets/flags/bo.svg"),
	bq: require("../assets/flags/bq.svg"),
	br: require("../assets/flags/br.svg"),
	bs: require("../assets/flags/bs.svg"),
	bt: require("../assets/flags/bt.svg"),
	bv: require("../assets/flags/bv.svg"),
	bw: require("../assets/flags/bw.svg"),
	by: require("../assets/flags/by.svg"),
	bz: require("../assets/flags/bz.svg"),
	ca: require("../assets/flags/ca.svg"),
	cc: require("../assets/flags/cc.svg"),
	cd: require("../assets/flags/cd.svg"),
	cf: require("../assets/flags/cf.svg"),
	cg: require("../assets/flags/cg.svg"),
	ch: require("../assets/flags/ch.svg"),
	ci: require("../assets/flags/ci.svg"),
	ck: require("../assets/flags/ck.svg"),
	cl: require("../assets/flags/cl.svg"),
	cm: require("../assets/flags/cm.svg"),
	cn: require("../assets/flags/cn.svg"),
	co: require("../assets/flags/co.svg"),
	cr: require("../assets/flags/cr.svg"),
	cu: require("../assets/flags/cu.svg"),
	cv: require("../assets/flags/cv.svg"),
	cw: require("../assets/flags/cw.svg"),
	cx: require("../assets/flags/cx.svg"),
	cy: require("../assets/flags/cy.svg"),
	cz: require("../assets/flags/cz.svg"),
	de: require("../assets/flags/de.svg"),
	dj: require("../assets/flags/dj.svg"),
	dk: require("../assets/flags/dk.svg"),
	dm: require("../assets/flags/dm.svg"),
	do: require("../assets/flags/do.svg"),
	dz: require("../assets/flags/dz.svg"),
	ec: require("../assets/flags/ec.svg"),
	ee: require("../assets/flags/ee.svg"),
	eg: require("../assets/flags/eg.svg"),
	eh: require("../assets/flags/eh.svg"),
	er: require("../assets/flags/er.svg"),
	es: require("../assets/flags/es.svg"),
	et: require("../assets/flags/et.svg"),
	eu: require("../assets/flags/eu.svg"),
	fi: require("../assets/flags/fi.svg"),
	fj: require("../assets/flags/fj.svg"),
	fk: require("../assets/flags/fk.svg"),
	fm: require("../assets/flags/fm.svg"),
	fo: require("../assets/flags/fo.svg"),
	fr: require("../assets/flags/fr.svg"),
	ga: require("../assets/flags/ga.svg"),
	gb: require("../assets/flags/gb.svg"),
	"gb-eng": require("../assets/flags/gb-eng.svg"),
	"gb-nir": require("../assets/flags/gb-nir.svg"),
	"gb-sct": require("../assets/flags/gb-sct.svg"),
	"gb-wls": require("../assets/flags/gb-wls.svg"),
	gd: require("../assets/flags/gd.svg"),
	ge: require("../assets/flags/ge.svg"),
	gf: require("../assets/flags/gf.svg"),
	gg: require("../assets/flags/gg.svg"),
	gh: require("../assets/flags/gh.svg"),
	gi: require("../assets/flags/gi.svg"),
	gl: require("../assets/flags/gl.svg"),
	gm: require("../assets/flags/gm.svg"),
	gn: require("../assets/flags/gn.svg"),
	gp: require("../assets/flags/gp.svg"),
	gq: require("../assets/flags/gq.svg"),
	gr: require("../assets/flags/gr.svg"),
	gs: require("../assets/flags/gs.svg"),
	gt: require("../assets/flags/gt.svg"),
	gu: require("../assets/flags/gu.svg"),
	gw: require("../assets/flags/gw.svg"),
	gy: require("../assets/flags/gy.svg"),
	hk: require("../assets/flags/hk.svg"),
	hm: require("../assets/flags/hm.svg"),
	hn: require("../assets/flags/hn.svg"),
	hr: require("../assets/flags/hr.svg"),
	ht: require("../assets/flags/ht.svg"),
	hu: require("../assets/flags/hu.svg"),
	id: require("../assets/flags/id.svg"),
	ie: require("../assets/flags/ie.svg"),
	il: require("../assets/flags/il.svg"),
	im: require("../assets/flags/im.svg"),
	in: require("../assets/flags/in.svg"),
	io: require("../assets/flags/io.svg"),
	iq: require("../assets/flags/iq.svg"),
	ir: require("../assets/flags/ir.svg"),
	is: require("../assets/flags/is.svg"),
	it: require("../assets/flags/it.svg"),
	je: require("../assets/flags/je.svg"),
	jm: require("../assets/flags/jm.svg"),
	jo: require("../assets/flags/jo.svg"),
	jp: require("../assets/flags/jp.svg"),
	ke: require("../assets/flags/ke.svg"),
	kg: require("../assets/flags/kg.svg"),
	kh: require("../assets/flags/kh.svg"),
	ki: require("../assets/flags/ki.svg"),
	km: require("../assets/flags/km.svg"),
	kn: require("../assets/flags/kn.svg"),
	kp: require("../assets/flags/kp.svg"),
	kr: require("../assets/flags/kr.svg"),
	kw: require("../assets/flags/kw.svg"),
	ky: require("../assets/flags/ky.svg"),
	kz: require("../assets/flags/kz.svg"),
	la: require("../assets/flags/la.svg"),
	lb: require("../assets/flags/lb.svg"),
	lc: require("../assets/flags/lc.svg"),
	li: require("../assets/flags/li.svg"),
	lk: require("../assets/flags/lk.svg"),
	lr: require("../assets/flags/lr.svg"),
	ls: require("../assets/flags/ls.svg"),
	lt: require("../assets/flags/lt.svg"),
	lu: require("../assets/flags/lu.svg"),
	lv: require("../assets/flags/lv.svg"),
	ly: require("../assets/flags/ly.svg"),
	ma: require("../assets/flags/ma.svg"),
	mc: require("../assets/flags/mc.svg"),
	md: require("../assets/flags/md.svg"),
	me: require("../assets/flags/me.svg"),
	mf: require("../assets/flags/mf.svg"),
	mg: require("../assets/flags/mg.svg"),
	mh: require("../assets/flags/mh.svg"),
	mk: require("../assets/flags/mk.svg"),
	ml: require("../assets/flags/ml.svg"),
	mm: require("../assets/flags/mm.svg"),
	mn: require("../assets/flags/mn.svg"),
	mo: require("../assets/flags/mo.svg"),
	mp: require("../assets/flags/mp.svg"),
	mq: require("../assets/flags/mq.svg"),
	mr: require("../assets/flags/mr.svg"),
	ms: require("../assets/flags/ms.svg"),
	mt: require("../assets/flags/mt.svg"),
	mu: require("../assets/flags/mu.svg"),
	mv: require("../assets/flags/mv.svg"),
	mw: require("../assets/flags/mw.svg"),
	mx: require("../assets/flags/mx.svg"),
	my: require("../assets/flags/my.svg"),
	mz: require("../assets/flags/mz.svg"),
	na: require("../assets/flags/na.svg"),
	nc: require("../assets/flags/nc.svg"),
	ne: require("../assets/flags/ne.svg"),
	nf: require("../assets/flags/nf.svg"),
	ng: require("../assets/flags/ng.svg"),
	ni: require("../assets/flags/ni.svg"),
	nl: require("../assets/flags/nl.svg"),
	no: require("../assets/flags/no.svg"),
	np: require("../assets/flags/np.svg"),
	nr: require("../assets/flags/nr.svg"),
	nu: require("../assets/flags/nu.svg"),
	nz: require("../assets/flags/nz.svg"),
	om: require("../assets/flags/om.svg"),
	pa: require("../assets/flags/pa.svg"),
	pe: require("../assets/flags/pe.svg"),
	pf: require("../assets/flags/pf.svg"),
	pg: require("../assets/flags/pg.svg"),
	ph: require("../assets/flags/ph.svg"),
	pk: require("../assets/flags/pk.svg"),
	pl: require("../assets/flags/pl.svg"),
	pm: require("../assets/flags/pm.svg"),
	pn: require("../assets/flags/pn.svg"),
	pr: require("../assets/flags/pr.svg"),
	ps: require("../assets/flags/ps.svg"),
	pt: require("../assets/flags/pt.svg"),
	pw: require("../assets/flags/pw.svg"),
	py: require("../assets/flags/py.svg"),
	qa: require("../assets/flags/qa.svg"),
	re: require("../assets/flags/re.svg"),
	ro: require("../assets/flags/ro.svg"),
	rs: require("../assets/flags/rs.svg"),
	ru: require("../assets/flags/ru.svg"),
	rw: require("../assets/flags/rw.svg"),
	sa: require("../assets/flags/sa.svg"),
	sb: require("../assets/flags/sb.svg"),
	sc: require("../assets/flags/sc.svg"),
	sd: require("../assets/flags/sd.svg"),
	se: require("../assets/flags/se.svg"),
	sg: require("../assets/flags/sg.svg"),
	sh: require("../assets/flags/sh.svg"),
	si: require("../assets/flags/si.svg"),
	sj: require("../assets/flags/sj.svg"),
	sk: require("../assets/flags/sk.svg"),
	sl: require("../assets/flags/sl.svg"),
	sm: require("../assets/flags/sm.svg"),
	sn: require("../assets/flags/sn.svg"),
	so: require("../assets/flags/so.svg"),
	sr: require("../assets/flags/sr.svg"),
	ss: require("../assets/flags/ss.svg"),
	st: require("../assets/flags/st.svg"),
	sv: require("../assets/flags/sv.svg"),
	sx: require("../assets/flags/sx.svg"),
	sy: require("../assets/flags/sy.svg"),
	sz: require("../assets/flags/sz.svg"),
	tc: require("../assets/flags/tc.svg"),
	td: require("../assets/flags/td.svg"),
	tf: require("../assets/flags/tf.svg"),
	tg: require("../assets/flags/tg.svg"),
	th: require("../assets/flags/th.svg"),
	tj: require("../assets/flags/tj.svg"),
	tk: require("../assets/flags/tk.svg"),
	tl: require("../assets/flags/tl.svg"),
	tm: require("../assets/flags/tm.svg"),
	tn: require("../assets/flags/tn.svg"),
	to: require("../assets/flags/to.svg"),
	tr: require("../assets/flags/tr.svg"),
	tt: require("../assets/flags/tt.svg"),
	tv: require("../assets/flags/tv.svg"),
	tw: require("../assets/flags/tw.svg"),
	tz: require("../assets/flags/tz.svg"),
	ua: require("../assets/flags/ua.svg"),
	ug: require("../assets/flags/ug.svg"),
	um: require("../assets/flags/um.svg"),
	us: require("../assets/flags/us.svg"),
	uy: require("../assets/flags/uy.svg"),
	uz: require("../assets/flags/uz.svg"),
	va: require("../assets/flags/va.svg"),
	vc: require("../assets/flags/vc.svg"),
	ve: require("../assets/flags/ve.svg"),
	vg: require("../assets/flags/vg.svg"),
	vi: require("../assets/flags/vi.svg"),
	vn: require("../assets/flags/vn.svg"),
	vu: require("../assets/flags/vu.svg"),
	wf: require("../assets/flags/wf.svg"),
	ws: require("../assets/flags/ws.svg"),
	xk: require("../assets/flags/xk.svg"),
	ye: require("../assets/flags/ye.svg"),
	yt: require("../assets/flags/yt.svg"),
	za: require("../assets/flags/za.svg"),
	zm: require("../assets/flags/zm.svg"),
	zw: require("../assets/flags/zw.svg"),
};

/**
 * Get the local flag asset for a given country code
 * @param countryCode - ISO 3166-1 alpha-2 country code (e.g., 'us', 'ca', 'nl')
 * @returns The local flag asset or null if not found
 */
export function getFlagAsset(countryCode: string): ImageSource | null {
	const normalizedCode = countryCode.toLowerCase();
	return flagAssets[normalizedCode] || null;
}

/**
 * Check if a flag exists for the given country code
 * @param countryCode - ISO 3166-1 alpha-2 country code
 * @returns Boolean indicating if the flag exists
 */
export function hasFlagAsset(countryCode: string): boolean {
	const normalizedCode = countryCode.toLowerCase();
	return normalizedCode in flagAssets;
}

/**
 * Get all available country codes that have flag assets
 * @returns Array of country codes
 */
export function getAvailableFlags(): string[] {
	return Object.keys(flagAssets);
}
